version: '2'
services:
  catinymessenger-app:
    image: catinymessenger
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - JHIPSTER_CACHE_REDIS_SERVER=redis://catinymessenger-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://catinymessenger-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=catinymessenger-cassandra
      - JHIPSTER_SLEEP=80 # gives time for uaa and the Cassandra cluster to start and execute the migration scripts
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
  catinymessenger-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: catinymessenger-cassandra
  #  catinymessenger-cassandra-node:
  #    image: cassandra:3.11.5
  #    environment:
  #      - CASSANDRA_SEEDS=catinymessenger-cassandra
  catinymessenger-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: catinymessenger-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
  catinymessenger-redis:
    extends:
      file: redis.yml
      service: catinymessenger-redis
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
#  jhipster-registry:
#    extends:
#      file: jhipster-registry.yml
#      service: jhipster-registry
#    environment:
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
