version: '2'
services:
  catinymessenger-cassandra:
    image: cassandra:3.11.5
    ports:
      - 12011:7000
      - 12012:7001
      - 12013:7199
      - 12010:9042
      - 12014:9160
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=512M
  catinymessenger-cassandra-node:
    image: cassandra:3.11.5
    environment:
      - CASSANDRA_SEEDS=catinymessenger-cassandra
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=512M
  catinymessenger-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: catinymessenger-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
